[package]
name = "points"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

[lib]
name = "points"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.6.8"
