[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-pack"
version = "0.0.2"
description = "Build and publish python packages from crates with pyo3 bindings"
exclude = ["get_fourtytwo/**/*", "integration-test/**/*", "ci/*"]
readme = "Readme.md"
repository = "https://github.com/pyo3/pyo3-pack"
license = "MIT OR Apache-2.0"
keywords = ["python", "ffi", "packaging", "pypi", "pyo3"]
categories = ["api-bindings", "development-tools::ffi", "command-line-utilities"]

[badges]
travis-ci = { repository = "PyO3/pyo3-pack" }
appveyor = { repository = "konstin/pyo3" }

[[bin]]
name = "pyo3-pack"

[lib]
name = "pyo3_pack"

[dependencies]
base64 = "0.9.2"
cargo_metadata = "0.6.0"
digest = { version = "0.7.5", features = ["std"] }
failure = "0.1.2"
keyring = "0.6.0"
reqwest = "0.8.7"
rpassword = "2.0.0"
serde_derive = "1.0.71"
serde_json = "1.0.24"
sha2 = "0.7.1"
structopt = "0.2.10"
target_info = "0.1.0"
toml = "0.4.6"
zip = "0.4.2"
serde = "1.0.71"
elfkit = { version = "0.0.6", optional = true }
tar = { version = "0.4.16", optional = true }
libflate = { version = "0.1.16", optional = true }
human-panic = "1.0.0"
regex = "1.0.2"
indicatif = "0.9.0"
atty = "0.2.11"

[dev-dependencies]
tempfile = "3.0.3"
indoc = "0.2.6"

[features]
default = ["auditwheel"]
auditwheel = ["elfkit"]
# sdist can be written, but those can not be installed
sdist = ["tar", "libflate"]

[workspace]
members = [
    "get_fourtytwo"
]
