name: pyo3-pack
version: 0.0.2
summary: Build and publish python packages from crates with pyo3 bindings
description: Build and publish crates with pyo3 bindings as python packages.

grade: stable
confinement: strict

parts:
  pyo3-pack:
    plugin: rust
    source: .
    build-attributes: [no-system-libraries]
    stage-packages: [libgmp10, libssl1.0.0, liblzma5, libgcrypt20, libgpg-error0]

apps:
  pyo3-pack:
    plugs: [home, network, dbus]
    command: pyo3-pack
